# Generated by Django 5.1.3 on 2024-12-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_bio_alter_user_email_alter_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='images',
        ),
    ]
