# Generated by Django 5.1.3 on 2024-12-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_image_user_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='images',
            new_name='pic',
        ),
    ]
