# Generated by Django 5.1.3 on 2024-12-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(blank=True, default='Profile/default_pic.jpg', null=True, upload_to='Profile/'),
        ),
    ]
